package fr.sorbonne_u.components.washingMachine;

public enum Program {
	COTON, COTONCI, MIX40C, SYNTETHETIQUES, COUETTE
	/* HIGIENE, BABY_CARE, TEXTILES_SPORT, DELICAT, NOIR_ECLAT,
	ANTITACHE, ULTRA_SILENCE, RAPIDE_30_MIN, PROGRAMME, TELECHARGE*/
}
